services:
  redis:
    image: redis:latest
    container_name: redisson-lock-redis
    hostname: localhost
    ports:
      - "127.0.0.1:6379:6379"
  mysql:
    image: mysql:latest
    container_name: redisson-lock-mysql
    hostname: localhost
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: redisson-lock
      MYSQL_ROOT_PASSWORD: admin
